$("#reportspage").hide();
$("#reportcontainer").click(function(){
    $("#home-page-wrapper").hide();
    $("#reportspage").show();
});
$("#homepage").click(function(){
    $("#home-page-wrapper").show();
    $("#reportspage").hide();
});
